import type { MdDungeon } from "../../db/types";

// Starter seed — the user's own fully-configured MD master (all dungeons,
// modes, MVP mobs, and reward items filled in from real play), exported via
// MDマスタ's export/import panel and adopted as the default starting point
// for a fresh install. Item values are the default quantity per clear: >0 =
// fixed/guaranteed reward, 0 = variable reward the user fills in per run.
// Inserted once on first run; the user can add/edit/archive afterward via
// MdMasterTable.
export const mdDungeonSeed: Omit<MdDungeon, "id">[] = [
  {
    name: "悔恨の墓",
    ctType: "weeklyTue12",
    items: {
      ミネアス: 40,
      エーテルアクアマリン: 0,
      宝箱: 4,
      白金: 4,
      金塊: 4,
      銀塊: 4,
    },
    sortOrder: 0,
    mvpMobs: ["ティアラ姫", "魔剣士サクライ"],
    archived: false,
    attemptsPerCycle: 2,
    requiredLevel: 260,
  },
  {
    name: "呪いの剣士",
    ctType: "daily",
    items: {},
    sortOrder: 1,
    mvpMobs: [],
  },
  {
    name: "変えられない最後",
    ctType: "weeklyTue12",
    items: {
      ウィグナー商会交換証: 100,
      呪いの象徴: 60,
      堕ちた蛇の象徴: 5,
      エーテルアクアマリン: 0,
      トリスカードの欠片: 0,
      "ガラシア・ネリウスカードの欠片": 0,
      "イルジェ・エル・ハイネンカードの欠片": 0,
      "オーレリー・プティカードの欠片": 0,
      ヨハンカードの欠片: 0,
      "ラライラ・ナザール・ウィグナーカードの欠片": 0,
      "エフェスト・バルター・メガスカードの欠片": 0,
      "イアナ・オペルタカードの欠片": 0,
      タンカードの欠片: 0,
      ギュンターカードの欠片: 0,
      "ラインハルト・レベンブルグカードの欠片": 0,
      "アイヴァン・ウィグナーカードの欠片": 0,
      "マリステラ・バルターカードの欠片": 0,
      "ヴィルヘルム・レベンブルグカードの欠片": 0,
      ラウラ・バルダリスカードの欠片: 0,
      リハルト・リハルトカードの欠片: 0,
      ナドヨカードの欠片: 0,
      リーカードの欠片: 0,
      "ハーウェル・メガス・バルターカードの欠片": 0,
    },
    sortOrder: 2,
    mvpMobs: ["侵食されたタン"],
    attemptsPerCycle: 2,
    requiredLevel: 275,
  },
  {
    name: "欺瞞の別荘",
    ctType: "weeklyTue12",
    items: {
      アメジストの欠片: 45,
      浄化図面の束: 0,
      浄化の聖水: 0,
      エーテルアクアマリン: 0,
    },
    sortOrder: 3,
    mvpMobs: ["シュラン", "デミフレイヤ"],
    attemptsPerCycle: 2,
    requiredLevel: 210,
  },
  {
    name: "旧バルター号捜索",
    ctType: "daily",
    items: { ウィグナー商会交換証: 20 },
    sortOrder: 4,
    mvpMobs: ["幽霊船の艦長"],
    requiredLevel: 260,
  },
  {
    name: "シミュレーション戦闘",
    ctType: "weeklyTue12",
    items: { 小さな氷華の魔石: 100, 氷華の魔石: 0, エーテルアクアマリン: 0 },
    sortOrder: 5,
    mvpMobs: ["Sユンケア"],
    requiredLevel: 220,
    attemptsPerCycle: 2,
  },
  {
    name: "星座の塔",
    ctType: "weeklyTue12",
    items: {
      メテオライトの欠片: 1,
      ナハトズィーガーの魂: 0,
      ベテルギウスの魂: 0,
    },
    sortOrder: 6,
    mvpMobs: [
      "ドレイク",
      "ミストレス",
      "オークロード",
      "オークヒーロー",
      "アトロス",
      "黒蛇王",
      "ドッペルゲンガー",
      "イグニゼム=セニア（一次職）（MVP）",
      "オシリス",
      "アモンラー",
      "バフォメット",
      "ダークロード",
      "マヤー",
      "イフリート",
      "ランドグリス",
      "瀕死のナハトズィーガー",
      "ベテルギウス",
    ],
    requiredLevel: 250,
  },
  {
    name: "生体工学研究所の記録（4th）",
    ctType: "weeklyTue12",
    items: {
      生体実験の破片: 3,
      思念のオーラ: 0,
      宝箱: 5,
      金塊: 2,
      銀塊: 2,
      白金: 2,
    },
    sortOrder: 7,
    mvpMobs: ["無名のソードマン（4thモード）（MVP）"],
    requiredLevel: 250,
    attemptsPerCycle: 2,
  },
  {
    name: "生命の殿堂",
    ctType: "weeklyTue12",
    items: {
      生命の真理: 1,
      生命の循環: 0,
      フローラルペガサスの象徴: 0,
      コーラルマリンの珊瑚: 0,
      メイプルツリーの枝: 0,
      モナークペンギンの氷結晶: 0,
    },
    sortOrder: 8,
    mvpMobs: ["次元犯罪者リゲル"],
    requiredLevel: 260,
    accountCharacterLimit: 15,
    modes: [
      { name: "難易度★", mvpMobs: ["次元犯罪者リゲル（難易度★）"] },
      { name: "難易度★★", mvpMobs: ["次元犯罪者リゲル（難易度★★）"] },
      { name: "難易度★★★", mvpMobs: ["次元犯罪者リゲル（難易度★★★）"] },
      {
        name: "難易度★★★★",
        mvpMobs: ["次元犯罪者リゲル（難易度★★★★）"],
      },
    ],
  },
  {
    name: "特異点 生体工学研究所",
    ctType: "weeklyTue12",
    items: {
      思念体の渇き: 60,
      古いカード帖: 2,
      白金: 4,
      金塊: 3,
      銀塊: 4,
      思念体の冷気: 0,
      思念体の憤怒: 0,
      豪華な宝箱: 0,
    },
    sortOrder: 9,
    mvpMobs: [],
    accountCharacterLimit: 7,
    requiredLevel: 275,
    modes: [
      { name: "マーガレッタ", mvpMobs: ["憤怒のマーガレッタ（インフェルノ）（MVP）"] },
      { name: "エレメス", mvpMobs: ["憤怒のエレメス（インフェルノ）（MVP）"] },
      { name: "エミュール", mvpMobs: ["憤怒のエミュール（インフェルノ）（MVP）"] },
      { name: "ハワード", mvpMobs: ["憤怒のハワード（インフェルノ）（MVP）"] },
      { name: "トレンティーニ", mvpMobs: ["憤怒のトレンティーニ（インフェルノ）（MVP）"] },
      { name: "アルフォシオ", mvpMobs: ["憤怒のアルフォシオ（インフェルノ）（MVP）"] },
      { name: "セシル", mvpMobs: ["憤怒のセシル（インフェルノ）（MVP）"] },
      { name: "ランデル", mvpMobs: ["憤怒のランデル（インフェルノ）（MVP）"] },
      { name: "セイレン", mvpMobs: ["憤怒のセイレン（インフェルノ）（MVP）"] },
      { name: "ガーティー", mvpMobs: ["憤怒のガーティー（インフェルノ）（MVP）"] },
      { name: "セリア", mvpMobs: ["憤怒のセリア（インフェルノ）（MVP）"] },
      { name: "チェン", mvpMobs: ["憤怒のチェン（インフェルノ）（MVP）"] },
      { name: "カトリーヌ", mvpMobs: ["憤怒のカトリーヌ（インフェルノ）（MVP）"] },
    ],
  },
  {
    name: "特異点 名もなき島",
    ctType: "weeklyTue12",
    items: {
      古いカード帖: 10,
      豪華な宝箱: 10,
      宝箱: 19,
      金塊: 17,
      銀塊: 18,
      暴食の宝玉: 200,
      暴食の魔石: 1,
      暴食の欠片: 0,
      白金: 17,
    },
    sortOrder: 10,
    mvpMobs: [],
    accountCharacterLimit: 7,
    requiredLevel: 260,
    modes: [
      {
        name: "インフェルノ",
        mvpMobs: [
          "暴食の堕ちた大神官（インフェルノ）",
          "暴食の魔王ヴェルゼブブ（インフェルノ）",
        ],
      },
      { name: "ノーマル", mvpMobs: ["暴食の堕ちた大神官（ノーマル）"] },
    ],
  },
  {
    name: "呪われた次元（4th）",
    ctType: "weeklyTue12",
    items: {
      時間の宝石: 200,
      時間の赤水晶: 50,
      凝縮した魔血: 50,
      凝固された魔力: 50,
      豪華な宝箱: 8,
      金塊: 17,
      宝箱: 17,
      白金: 17,
      銀塊: 17,
      時間の結晶: 50,
      輝く時間の宝石: 1,
    },
    sortOrder: 11,
    mvpMobs: [
      "堕落の魔眼（4th）",
      "呪殺のアムダライス（4th）",
      "呪殺のヒメルメズ（4th）",
    ],
    accountCharacterLimit: 7,
    requiredLevel: 250,
  },
  {
    name: "夢幻の迷宮",
    ctType: "weeklyTue12",
    items: {
      エーテルアクアマリン: 1,
      エーテルトパーズ: 0,
      "DV&シャドウ": 0,
      黄金の魔力結晶: 1,
    },
    sortOrder: 12,
    mvpMobs: [],
    requiredLevel: 220,
    accountCharacterLimit: 15,
    modes: [
      {
        name: "幻影",
        mvpMobs: [
          "迷宮のバフォメット",
          "混沌のゴーストリング",
          "不吉なタートルG",
          "オークヒーロー",
          "怨霊武士",
          "暴虐のシーラカンス",
          "マーガレッタ=ソリン",
          "真理の魔法使い",
          "ストームナイト",
          "輝くベアドール",
          "無口なマヤー",
          "ファラオ",
          "レヤック",
          "覚醒クトルラナックス",
          "深海のクラーケン",
          "深海の魔女",
        ],
      },
      {
        name: "亜空",
        mvpMobs: [
          "ボミ",
          "不吉なソリッドタートル",
          "怒りのドラキュラ",
          "硬化ムスペルスコール",
          "R48-85-ベスティア",
          "変異のシーラカンス",
          "セシル=ディモン",
          "ランドグリス",
          "ゴピニク",
          "怒りの月夜花",
          "ゴブリンキング",
          "古のタオグンカ",
          "ボーンデータルザウルス",
          "R001-ベスティア",
          "死者の案内人",
          "亜空の月夜花",
          "亜空のハティー",
          "亜空のストームナイト",
        ],
      },
    ],
  },
  {
    name: "封じられた不死者",
    ctType: "weeklyTue12",
    items: {
      小さな氷華の魔石: 60,
      氷華の魔石: 0,
      エーテルアクアマリン: 0,
      神聖な猫のひげ: 100,
      蛇神の鱗: 10,
    },
    sortOrder: 13,
    mvpMobs: ["究極のラスガンド"],
    requiredLevel: 260,
    attemptsPerCycle: 2,
  },
  {
    name: "ファロス燈台地下迷宮",
    ctType: "weeklyTue12",
    items: { 壊れた高純度の魔法石: 0, 壊れた魔法石: 0 },
    sortOrder: 14,
    mvpMobs: [],
    accountCharacterLimit: 15,
  },
  {
    name: "特異点 タナトスタワー",
    ctType: "weeklyTue12",
    items: {},
    mvpMobs: [],
    accountCharacterLimit: 7,
    requiredLevel: 275,
    sortOrder: 15,
    archived: false,
    modes: [
      {
        name: "インフェルノ",
        mvpMobs: [
          "傲慢なタナトス（インフェルノ）",
          "傲慢な暴走したタナトス（インフェルノ）",
        ],
      },
      {
        name: "チャレンジ",
        mvpMobs: [
          "傲慢なタナトス（チャレンジ）",
          "傲慢な暴走したタナトス（チャレンジ）",
        ],
      },
    ],
  },
];
